version: '2'

output: prefixed
silent: true

vars:
  pwd:
    sh: pwd
  random_uuid:
    sh: cat /proc/sys/kernel/random/uuid

includes:
  go: tasks/go.yml

tasks:
  rr:
    cmds:
      - task: reset
      - task: build
      - mkdir -p .runners/{{ .random_uuid }}
      - SNAKE_NAME={{ .random_uuid }}
        SNAKE_TOKEN_PATH=.runners/{{.random_uuid}}/token
        SNAKE_SSH_KEY_PATH=.runners/{{.random_uuid}}/id_rsa
        ./snake-runner -c ./conf/snake.dev.conf
