version: '2'

output: prefixed
silent: true

vars:
  pwd:
    sh: pwd
  random_uuid:
    sh: cat /proc/sys/kernel/random/uuid

tasks:
  generate:
    sources:
      - '*.go'
    generates:
      - '*_gen.go'
    cmds:
      - go generate

  build:
    desc: build go code
    deps: [generate]
    cmds:
      - go build

  reset:
    cmds:
      - rm -f conf/token conf/sshkey conf/sshkey.pub

  rr:
    cmds:
      - task: reset
      - task: build
      - mkdir -p .runners/{{ .random_uuid }}
      - SNAKE_NAME={{ .random_uuid }}
        SNAKE_TOKEN_PATH=.runners/{{.random_uuid}}/token
        SNAKE_SSH_KEY_PATH=.runners/{{.random_uuid}}/id_rsa
        ./snake-runner -c ./conf/snake.dev.conf
