version: '2'

output: prefixed
silent: true

expansions: 3

vars:
  pwd:
    sh: pwd
  random_uuid:
    sh: cat /proc/sys/kernel/random/uuid
  token: ""
  major_minor:
    sh: "git describe --tags --abbrev=0"
  patch:
    sh: "git rev-list $(git describe --tags --abbrev=0)..HEAD --count"
  version: "{{.major_minor}}.{{.patch}}"
  commit:
    sh: "git rev-parse --short HEAD"

includes:
  go: tasks/go.yml
  docker: tasks/docker.yml

tasks:
  version:
    desc: print version
    cmds:
      - printf "%s" "{{.version}}"
  rr:
    cmds:
      - task: go:build
      - mkdir -p .runners/{{.random_uuid}}
      - SNAKE_NAME={{.random_uuid}}
        SNAKE_ACCESS_TOKEN_PATH=.runners/{{.random_uuid}}/token
        SNAKE_REGISTRATION_TOKEN={{.token}}
        SNAKE_SSH_KEY_PATH=.runners/{{.random_uuid}}/id_rsa
        SNAKE_PIPELINES_DIR=.runners/{{.random_uuid}}/pipelines
        SNAKE_LOG_TRACE=true
        ./snake-runner -c ./conf/dev.conf
  dock:
    cmds:
      - task: docker:snake-runner@build
      - docker run -it
          -e SNAKE_NAME={{.random_uuid}}
          -e SNAKE_MASTER_ADDRESS=localhost:7990
          -e SNAKE_REGISTRATION_TOKEN={{.token}}
          -e SNAKE_LOG_DEBUG=true
          -e SNAKE_LOG_TRACE=true
          -e SNAKE_DOCKER_NETWORK=host
          -e 'SNAKE_DOCKER_VOLUMES=["/var/run/docker.sock:/var/run/docker.sock"]'
          -v /var/lib/snake-runner/secrets:{{.pwd}}/secrets
          -v /var/run/docker.sock:/var/run/docker.sock
          --rm
          --network host
          reconquest/snake-runner:latest
