version: '2'

vars:
  version:
    sh: git describe --tags | sed 's/\-/./g'

tasks:
  generate:
    cmds:
      - go generate ./...
    status:
      - ls cmd/*/*_gen.go

  build:
    desc: build go code
    deps: [generate]
    cmds:
      - 'echo Building version: {{ .version }} >&2'
      - go build
          -ldflags="-X=main.version={{.version}}"
          ./cmd/snake-runner

  build_docker:
    desc: build go code for docker
    deps: [generate]
    cmds:
      - 'echo Building version: {{ .version }}-docker >&2'
      - CGO_ENABLED=0 go build
          -o snake-runner.docker
          -ldflags="-X=main.version={{.version}}-docker"
          ./cmd/snake-runner

