version: '3'

tasks:
  generate:
    desc: run go generate
    cmds:
      - grep -lr 'go:generate' ./cmd/ ./internal/ | xargs -n1 -I{} -P12 go generate -x {}
    sources:
      - '**/*.go'
    generates:
      - '**/*_gen.go'
    method: checksum

  build:
    desc: build go code
    deps: [generate]
    cmds:
      - 'echo Building version: {{.version}}-{{.commit}} >&2'
      - go build
          -ldflags="-X=main.version={{.version}}-{{.commit}}"
          ./cmd/snake-runner

  build_docker:
    desc: build go code for docker
    deps: [generate]
    cmds:
      - 'echo Building version: {{.version}}-{{.commit}}-docker >&2'
      - CGO_ENABLED=0 go build
          -o snake-runner.docker
          -ldflags="-X=main.version={{.version}}-{{.commit}}-docker"
          ./cmd/snake-runner
